version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      target: frontend
    image: frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
      target: backend
    image: backend:latest
    ports:
      - "8000:8000"
